name: Feudalism
version: 0.00.002
author: Hafixion
depend:
  - Towny
api-version: 1.16
main: com.github.hafixion.FeudalismMain

commands:
  townruin:
    description: Checks if town is ruined
    usage: /townruin <town>/purge
