name: Feudalism
version: 0.00.002
author: Hafixion
depend:
  - Towny
api-version: 1.16
main: com.stoneskies.feudalism.FeudalismMain

commands:
  fd:
    description: The base feudalism command
